version: '3.9'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - 'put:/data/mongodb'

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    volumes:
      - 'put:/data/rabbitmq'

  api-gateway:
    restart: always
    build:
      context: ./src/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3010:80"
    volumes:
      - ./src/api-gateway:/app/

  auth:
    restart: always
    build:
      context: ./src/auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "3020:80"
    volumes:
      - ./src/auth:/app/

  user-setting:
    restart: always
    build:
      context: ./src/user-setting
      dockerfile: Dockerfile
    container_name: user-setting
    ports:
      - "3030:80"
    volumes:
      - ./src/user-setting:/app/

  book:
    restart: always
    build:
      context: ./src/book
      dockerfile: Dockerfile
    container_name: book
    ports:
      - "3040:80"
    volumes:
      - ./src/book:/app/

volumes:
  put:
    driver: local


